SELECT COL1,COL2,COL3, COL4
FROM R2 
MINUS 
SELECT R.COL1,R.COL2,R.COL3,R.COL4 
FROM R2 R JOIN R2 RR 
ON 
( NVL(TO_CHAR(R.COL1),' ')=NVL(TO_CHAR(RR.COL2),' ') AND NVL(TO_CHAR(R.COL2),' ')=NVL(TO_CHAR(RR.COL1),' ')
AND NVL(TO_CHAR(R.COL3),' ')=NVL(TO_CHAR(RR.COL3),' ') AND NVL(TO_CHAR(R.COL4),' ')=NVL(TO_CHAR(RR.COL4),' '))
AND R.ROWID<RR.ROWID;
