CREATE TABLE INITW
(NAMEP VARCHAR(50),
VALUEP VARCHAR(255))
ORGANIZATION EXTERNAL
(TYPE ORACLE_LOADER
DEFAULT DIRECTORY STUD
ACCESS PARAMETERS
(RECORDS DELIMITED BY NEWLINE
NOBADFILE
nologfile
FIELDS TERMINATED BY '='
REJECT ROWS WITH ALL NULL FIELDS)
LOCATION ('init.ora'))
REJECT LIMIT UNLIMITED;

SELECT *
FROM INITW;



SELECT LENGTH(VALUEP)-LENGTH(REPLACE(VALUEP, ':', ''))  "Ctl_files_cnt"
FROM INITW
WHERE NAMEP='control_files';

DROP TABLE INITW;
